### ISSUE TITLE
Error when installing via oaklib: subprocess-exited-with-error

### ISSUE THREAD

**Issue by anitacaron** [fastobo/fastobo-py#306]
I tried installing oak versions 0.1.32-0.1.36 and got this error for each.

```shell
Collecting fastobo~=0.12.1
  Using cached fastobo-0.12.1.tar.gz (20.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 13, in <module>
          import setuptools_rust as rust
        File "/private/var/folders/tt/t62pcpnn5bvbgf27x_pj70kr0000gp/T/pip-build-env-lsx2rjf7/overlay/lib/python3.9/site-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/private/var/folders/tt/t62pcpnn5bvbgf27x_pj70kr0000gp/T/pip-build-env-lsx2rjf7/overlay/lib/python3.9/site-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I could solve the problem installing setuptools using the command line `python3 -m pip install --upgrade pip setuptools wheel`.
However, Chris Mungall asked to create this issue so OAK would be easier to install.

**Comment by althonos** [comment]
Hi Anita!

This problem seems to be linked with MacOS management of Python in particular, because normally I've setup everything so that `pip` automatically installs build requirements (`setuptools` and `setuptools-rust`) for building the package.
